/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./stitch_html/*.html", "./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#adc6ff",
        "outline": "#767575",
        "on-background": "#e7e5e5",
        "on-secondary-fixed-variant": "#5a5b63",
        "surface-container-lowest": "#000000",
        "on-primary-fixed-variant": "#0058bb",
        "tertiary-fixed": "#69f6b8",
        "surface-container-highest": "#252626",
        "on-primary-container": "#bcd0ff",
        "on-surface-variant": "#acabaa",
        "surface": "#0e0e0e",
        "on-secondary-fixed": "#3e3f47",
        "tertiary": "#9bffce",
        "secondary-container": "#3a3b43",
        "on-error-container": "#ff9993",
        "on-secondary-container": "#bfbec8",
        "background": "#0e0e0e",
        "on-tertiary-fixed": "#00452d",
        "on-primary-fixed": "#003d85",
        "secondary-fixed-dim": "#d4d3dd",
        "primary-fixed": "#d8e2ff",
        "on-tertiary": "#006443",
        "surface-bright": "#2b2c2c",
        "on-error": "#490106",
        "inverse-on-surface": "#565555",
        "error-dim": "#bb5551",
        "tertiary-fixed-dim": "#58e7ab",
        "surface-container-low": "#131313",
        "secondary-fixed": "#e3e1ec",
        "surface-container-high": "#1f2020",
        "primary-fixed-dim": "#c2d4ff",
        "secondary-dim": "#9d9da6",
        "inverse-surface": "#fcf9f8",
        "secondary": "#9d9da6",
        "outline-variant": "#484848",
        "error-container": "#7f2927",
        "inverse-primary": "#005bc2",
        "primary-dim": "#97b9ff",
        "surface-variant": "#252626",
        "error": "#ee7d77",
        "tertiary-container": "#69f6b8",
        "surface-dim": "#0e0e0e",
        "on-tertiary-fixed-variant": "#006544",
        "tertiary-dim": "#58e7ab",
        "primary-container": "#004493",
        "surface-container": "#191a1a",
        "on-surface": "#e7e5e5",
        "on-tertiary-container": "#005a3c",
        "on-secondary": "#1f2027",
        "primary": "#adc6ff",
        "on-primary": "#003d87"
      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: { "DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem" },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
};
